name: bayesian_stardew_env
dependencies:
- python==3.11.5
- numpy==1.26.0
- pandas==2.1.1
- jupyter==1.0.0
- matplotlib==3.7.2
- plotly==5.9.0
- pip=23.3
- pip:
  - jupyter_contrib_nbextensions==0.7.0
